sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
language: php
php:
  - 7.0
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
 cache:
   apt: true
   directories: $HOME/.composer/cache
before_script:
  # disable xdebug for perf
  - phpenv config-rm xdebug.ini
  # Get latest version of composer
  - composer selfupdate